version: '3.8'
services:
  db:
    image: postgres:13.8
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpwd
      POSTGRES_DB: testdb
    volumes:
      - serverDB:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          memory: 4G
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pguser -d testdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  pgadmin:
    image: dpage/pgadmin4:5.7
    ports:
      - "5050:5050"
    environment:
      PGADMIN_DEFAULT_EMAIL: pguser@mail.ru
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

volumes:
  serverDB: