services:
  db:
    image: postgres:13.8
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpwd
      POSTGRES_DB: testdb
    volumes:
      - serverDB:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          memory: 4G
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pguser -d testdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  pgadmin:
    image: dpage/pgadmin4:5.7
    ports:
      - "5050:5050"
    environment:
      PGADMIN_DEFAULT_EMAIL: pguser@mail.ru
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  jira-connector:
    build:
      context: ./jira-connector
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
      - "8081:8081"
    environment:
      - ENV=PRODUCTION
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpwd
      - POSTGRES_DB=testdb
      - POSTGRES_POOL_SIZE=10
      - BASE_URL=https://issues.apache.org/jira/rest/api/2
      - MAX_CONNECTIONS=20
      - RETRY_COUNT=1
      - MAX_RESULTS=50
      - GRPC_PORT=9090
      - HTTP_PORT=8081
      - HOST=0.0.0.0
    depends_on:
      db:
        condition: service_healthy

  analytics:
    build:
      context: ./analytics
      dockerfile: Dockerfile
    expose:
      - "8084:8084"
    depends_on:
      db:
        condition: service_healthy

  resources:
    build:
      context: ./analytics
      dockerfile: Dockerfile
    expose:
      - "8085:8085"
    depends_on:
      db:
        condition: service_healthy

volumes:
  serverDB: