-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS Projects
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      TEXT,
    key        TEXT UNIQUE NOT NULL,
    lastUpdate TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Author
(
    id   serial PRIMARY KEY,
    name TEXT
);

CREATE TABLE IF NOT EXISTS Issue
(
    id          serial PRIMARY KEY,
    projectId   INT         NOT NULL,
    FOREIGN KEY (projectId) REFERENCES Projects (id) ON DELETE CASCADE ON UPDATE CASCADE,
    authorId    INT         NOT NULL,
    FOREIGN KEY (authorId) REFERENCES Author (id) ON DELETE CASCADE ON UPDATE CASCADE,
    assigneeId  INT         NOT NULL,
    key         TEXT UNIQUE NOT NULL,
    summary     TEXT,
    description TEXT,
    type        TEXT,
    priority    TEXT,
    status      TEXT,
    createdTime TIMESTAMP WITHOUT TIME ZONE,
    closedTime  TIMESTAMP WITHOUT TIME ZONE,
    updatedTime TIMESTAMP WITHOUT TIME ZONE,
    timeSpent   INT
);

CREATE TABLE IF NOT EXISTS StatusChanges
(
    issueId    INT NOT NULL,
    FOREIGN KEY (issueId) REFERENCES Issue (id) ON DELETE CASCADE ON UPDATE CASCADE,
    authorId   INT NOT NULL,
    FOREIGN KEY (authorId) REFERENCES Author (id) ON DELETE CASCADE ON UPDATE CASCADE,
    changeTime TIMESTAMP WITHOUT TIME ZONE,
    fromStatus TEXT,
    toStatus   TEXT
);

CREATE TABLE IF NOT EXISTS OpenTaskTime
(
    projectId INT         NOT NULL,
    FOREIGN KEY (projectId) REFERENCES Projects (id) ON DELETE CASCADE ON UPDATE CASCADE,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    data json
);

CREATE TABLE IF NOT EXISTS TaskPriorityCount
(
    projectId INT         NOT NULL,
    FOREIGN KEY (projectId) REFERENCES Projects (id) ON DELETE CASCADE ON UPDATE CASCADE,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    data json
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS "OpenTaskTime";
DROP TABLE IF EXISTS "TaskPriorityCount";
DROP TABLE IF EXISTS "StatusChanges";
DROP TABLE IF EXISTS "Issue";
DROP TABLE IF EXISTS "Author";
DROP TABLE IF EXISTS "Projects";
-- +goose StatementEnd